version: 2
updates:
  # Maintenance des GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintenance des images docker-compose
  - package-ecosystem: "docker-compose"
    directory: "/docker/traefik"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/docker/monitoring"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/docker/stateful/redis"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/docker/stateful/postgres"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/docker/app/immich"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/docker/app/nextcloud"
    schedule:
      interval: "weekly"
