---
# ========================================
# Defaults: docker
# ========================================

# Configuration log rotation
docker_log_max_size: "50m"
docker_log_max_file: "5"

# Network
proxy_network_name: "traefik-proxy"

# GPU (conditionnel depuis group_vars)
enable_gpu: false
