services:
  immich-postgres:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment to use HDD-optimized settings instead of SSD (default)
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      - ${DATA_PATH}/immich/postgres:/var/lib/postgresql/data
      - ./init-immich-db.sql:/docker-entrypoint-initdb.d/init.sql
    shm_size: 128mb
    networks:
      - default
      - proxy

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    volumes:
      - /mnt/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    depends_on:
      - immich-postgres
      - immich-machine-learning
    restart: always
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich-http.rule=Host(`${IMMICH_DOMAIN}`)"
      - "traefik.http.routers.immich-http.entrypoints=web"
      - "traefik.http.routers.immich-http.service=immich"
      - "traefik.http.routers.immich-https.rule=Host(`${IMMICH_DOMAIN}`)"
      - "traefik.http.routers.immich-https.entrypoints=websecure"
      - "traefik.http.routers.immich-https.service=immich"
      - "traefik.http.routers.immich-https.tls=true"
{% if enable_letsencrypt %}
      - "traefik.http.routers.immich-https.tls.certresolver=letsencrypt"
{% endif %}
      - "traefik.http.services.immich.loadbalancer.server.port=2283"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${DATA_PATH}/immich/model-cache:/cache
    env_file: .env
    restart: always
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    name: ${PROXY_NETWORK}
    external: true
