---
- name: Créer les répertoires de données
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ data_path }}/jellyfin/config"
    - "{{ data_path }}/jellyfin/cache"
    - "{{ docker_compose_path }}/jellyfin"

- name: Générer le fichier .env
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ docker_compose_path }}/jellyfin/.env"
    mode: '0600'

- name: Générer le fichier docker-compose
  ansible.builtin.template:
    src: ../../../docker/app/jellyfin/docker-compose.yml
    dest: "{{ docker_compose_path }}/jellyfin/docker-compose.yml"
    mode: '0644'

- name: Démarrer Jellyfin
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_path }}/jellyfin"
    state: present
    pull: always
