---
# ========================================
# Handlers: monitoring
# ========================================

- name: restart monitoring
  community.docker.docker_compose_v2:
    project_src: "{{ storage.ansible.compose }}/monitoring"
    state: restarted
  listen: restart monitoring
