---
# ========================================
# Handlers: monitoring
# ========================================

- name: restart monitoring
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_path }}/monitoring"
    state: restarted
  listen: restart monitoring
