---
# ========================================
# Handlers: docker
# ========================================

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
  listen: restart docker
