---
- name: Créer les répertoires de données Immich
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "1000"
    group: "1000"
  loop:
    - "{{ data_path }}/immich/upload"
    - "{{ data_path }}/immich/model-cache"
    - "{{ docker_compose_path }}/immich"

- name: Créer le répertoire de données PostgreSQL Immich
  ansible.builtin.file:
    path: "{{ data_path }}/immich/postgres"
    state: directory
    mode: '0700'
    owner: "999" # postgres
    group: "999"
    recurse: yes

- name: Générer le script d'initialisation PostgreSQL
  ansible.builtin.template:
    src: init-db.sql.j2
    dest: "{{ docker_compose_path }}/immich/init-immich-db.sql"
    mode: '0644'

- name: Générer le fichier .env
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ docker_compose_path }}/immich/.env"
    mode: '0600'

- name: Générer le fichier docker-compose
  ansible.builtin.template:
    src: ../../../docker/app/immich/docker-compose.yml
    dest: "{{ docker_compose_path }}/immich/docker-compose.yml"
    mode: '0644'
    trim_blocks: true
    lstrip_blocks: true

- name: Démarrer Immich
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_path }}/immich"
    state: present
    pull: always
