---
- name: Créer les répertoires de données Immich
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ common_system_user }}"
    group: "{{ common_system_group }}"
  loop:
    - "{{ storage.ansible.compose }}/immich"

- name: Créer le répertoire de données PostgreSQL Immich
  ansible.builtin.file:
    path: "{{ storage.databases.immich }}"
    state: directory
    mode: '0700'
    owner: "999" # postgres
    group: "999"
    recurse: yes

- name: Générer le script d'initialisation PostgreSQL
  ansible.builtin.template:
    src: init-db.sql.j2
    dest: "{{ storage.ansible.compose }}/immich/init-immich-db.sql"
    mode: '0644'

- name: Générer le fichier .env
  ansible.builtin.template:
    src: immich.env.j2
    dest: "{{ storage.ansible.compose }}/immich/.env"
    mode: '0600'

- name: Copier les requêtes personnalisées postgres-exporter
  ansible.builtin.copy:
    src: ../../../ansible/roles/monitoring/files/postgres-exporter-queries.yaml
    dest: "{{ storage.ansible.compose }}/immich/postgres-exporter-queries.yaml"
    mode: '0644'

- name: Générer le fichier docker-compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ storage.ansible.compose }}/immich/docker-compose.yml"
    mode: '0644'
    trim_blocks: true
    lstrip_blocks: true

- name: Démarrer Immich
  community.docker.docker_compose_v2:
    project_src: "{{ storage.ansible.compose }}/immich"
    state: present
    pull: always
