name: network

services:
  network-holder:
    image: alpine:latest
    container_name: network_holder
    command: /bin/sh -c "while true; do sleep 3600; done"
    networks:
      - proxy-nw

networks:
  proxy-nw:
    name: proxy-nw
    driver: bridge